//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market_project__E.F
{
    using System;
    using System.Collections.Generic;
    
    public partial class import_permession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public import_permession()
        {
            this.Import_Quantity = new HashSet<Import_Quantity>();
        }
    
        public int Iper_num { get; set; }
        public int item_id { get; set; }
        public string suplier_email { get; set; }
        public string store_name { get; set; }
        public Nullable<System.DateTime> Iper_date { get; set; }
    
        public virtual item item { get; set; }
        public virtual supplier supplier { get; set; }
        public virtual store store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Import_Quantity> Import_Quantity { get; set; }
    }
}
