//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market_project__E.F
{
    using System;
    using System.Collections.Generic;
    
    public partial class Import_Quantity
    {
        public int Iper_num { get; set; }
        public int item_id { get; set; }
        public string suplier_email { get; set; }
        public string store_name { get; set; }
        public int I_quantity { get; set; }
        public Nullable<System.DateTime> Prod_date { get; set; }
        public Nullable<System.DateTime> Exp_date { get; set; }
    
        public virtual import_permession import_permession { get; set; }
        public virtual store store { get; set; }
        public virtual item item { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
